apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - edge_model.yaml
  - cloud_model.yaml
  - joininference.yaml
images:
    - name: cloud-image:placeholder
      # modify the following images
      newName: cr.scut-smil.cn/sedna-learning/jointinference-image-classification-cloud
      newTag: v1.3.0test
    - name: edge-image:placeholder
      # modify the following images
      newName: cr.scut-smil.cn/sedna-learning/jointinference-image-classification-edge
      newTag: v1.3.0test
patches:
  - target:
      group: sedna.io
      version: v1alpha1
      kind: Model
      name: image-classification-inference-mbv2-shallow-model
    # modify the following model url
    patch: |-
      - op: replace
        path: /spec/url
        value: "s3://cloud-edge/resnet152_shallow.pts"
  - target:
      group: sedna.io
      version: v1alpha1
      kind: Model
      name: image-classification-inference-mbv2-deep-model
    # modify the following model url
    patch: |-
      - op: replace
        path: /spec/url
        value: "s3://cloud-edge/resnet152_deep.pts"
  - target:
      group: sedna.io
      version: v1alpha1
      kind: JointInferenceService
      name: image-classification-jointinference-example
    # modify the following inferred device
    patch: |-
      - op: replace
        path: /spec/edgeWorker/template/spec/containers/0/env/0/value
        value: "cuda"
  - target:
      group: sedna.io
      version: v1alpha1
      kind: JointInferenceService
      name: image-classification-jointinference-example
    # modify the following inferred device
    patch: |-
      - op: replace
        path: /spec/cloudWorker/template/spec/containers/0/env/0/value
        value: "cuda"
  - target:
      group: sedna.io
      version: v1alpha1
      kind: JointInferenceService
      name: image-classification-jointinference-example
    # modify the following dataset path
    patch: |-
      - op: replace
        path: /spec/edgeWorker/template/spec/containers/0/env/1/value
        value: "s3://cloud-edge/imagenet1000"