apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    s3-endpoint: ceph-s3-b7-1.scut-smil.cn # replace with your s3 endpoint
    s3-usehttps: "1" # by default 1, if testing with minio you can set to 0
stringData:
  ACCESS_KEY_ID: EGKIKHO2SD0X2ILV4K67
  SECRET_ACCESS_KEY: UDkZAbj0gZXIKGRCAjYMav8bqQr4zmOXSa02SRDF

  # python download.py s3://cloud-edge/mobilenet_v2_deep.pts  .